//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/octacian/backroom/api/db"
)

type Record struct {
	UUID db.UUID `sql:"primary_key"`
	Cage string
	Data db.JSONB
}
